spring:
  shardingsphere:
    datasource:
      names: db1, db2
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://hitachi-iot-test-rds.cath6q1djhtk.rds.cn-northwest-1.amazonaws.com.cn:3306/shardingsphere_1
        username: hitachi
        password: hitachi_2023
      db2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://hitachi-iot-test-rds.cath6q1djhtk.rds.cn-northwest-1.amazonaws.com.cn:3306/shardingsphere_2
        username: hitachi
        password: hitachi_2023
    sharding:
      tables:
        student:
          actual-data-nodes: db1.tb_student_$->{1..3},db2.tb_student_$->{1..3}
          database-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.shardingsphere.sharding.jpa.algorithm.DatabasePreciseShardingAlgorithm
          table-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.shardingsphere.sharding.jpa.algorithm.TablePreciseShardingAlgorithm
    readwrite_splitting:
        dataSources:
          db:
            type: Static
            load-balancer-name: round_robin
            props:
               write-data-source-name: db1
               read-data-source-names: db2
        loadBalancers:
          round_robin:
            type: ROUND_ROBIN